#

language: python
python:
    - "2.7"

env:
    - PLATFORMIO_CI_SRC=examples/AT-bridge
    - PLATFORMIO_CI_SRC=examples/hwserial_example
    - PLATFORMIO_CI_SRC=examples/altsoftserial_example

install:
    - pip install -U platformio
    - platformio lib -g install 73 #altsoftserial

script:
    - platformio ci --lib="." --board=megaatmega2560 
