# language: python
# python:
#     - "2.7"
#
# install:
#     - pip install -U platformio
#
# script:
#     - platformio run


#
# Template #2: The project is intended to by used as a library with examples
#

language: python
python:
    - "2.7"

env:
    - PLATFORMIO_CI_SRC=examples/AT-bridge
    - PLATFORMIO_CI_SRC=examples/example1

install:
    - pip install -U platformio

script:
    - platformio ci --lib="." --board=uno 
